Handle commitish strings & ".x"
bendrucker/exact-version pull request #1
Opened 2018-03-12 20:19 UTC by jacobq

This PR makes the following changes:

* Correctly detect ranges specified with ".x" notation, e.g. `1.0.x` 
* Improve test coverage, e.g. commitish URLs with exact (e.g. `#hash`) and range (e.g. `#semver:~1.0.0`)
* Update deps:
  - tape: 4.0.0 -> 4.9.0
  - standard: 4.0.0 -> 11.0.0
* Drop support for node versions older than oldest maintenance release (4.x):
* Bump version number to `1.1.0`

(see https://docs.npmjs.com/files/package.json#dependencies)

2018-03-12 21:45 UTC, bendrucker commented
Hi, I just updated standard. Tape did not need updating, your change was a noop and just forced a newer version that was previously allowed. Please don't make any changes to the package. 

Updating necessary deps is ok but bumping the version or making other changes is poor PR etiquette.

I will try to clean this up and merge later this afternoon.

2018-03-12 22:12 UTC, jacobq commented
@bendrucker Thanks for your reply. Per your request I've reverted the `package.json` changes except for bumping `standard` from `^4.0.0` to `^11.0.0`. I wasn't trying to have bad PR etiquette; I've just found that often the authors/maintainers of projects that are this old/inactive do not want to invest any effort in them, so I was trying to make things easy. I appreciate you being willing to merge & publish and updated version.

2018-03-12 22:24 UTC, bendrucker commented
That's ok, I appreciate the contribution. Trying to make things effort-free is nice but part of that is minimizing the change set.

The changes to the source are more substantial than expected so I'll leave some comments and we'll work on this a bit more.

2018-03-12 22:28 UTC, jacobq commented
I'll rebase this PR w/ your new commits on master in a moment. Feel free to edit anything however you like. All I really care about is that the test suite passes.

2018-03-12 22:42 UTC, bendrucker requested changes
Left a lot of comments. I care most about getting the tests to a more readable place, then focusing on the source.

2018-03-12 22:42 UTC, bendrucker commented on .travis.yml
> +  - "4"
Please remove travis changes. I updated the node versions to 4/6/8. The `npm test` script is the default. And I don't want caching, that's for big projects.

2018-03-12 22:42 UTC, bendrucker commented on .travis.yml
> +cache:
Remove this, caching is for projects with huge dep graphs

2018-03-12 22:42 UTC, bendrucker commented on .travis.yml
> +script:
This is the default, remove it please. And generally don't change the CI config for a PR unless it's related (e.g. removing or adding node version support).

2018-03-12 22:42 UTC, bendrucker commented on index.js
> +const rangeRegEx = /^$|[\^*~<>|]|(\d+\.x)|(\d+(\.\d)*\s*-\s*\d+(\.\d)*)/
This regex is a lot hairier than the original and I'm not sure if I'm ok with munging all this logic into a single line. I'll come back to this.

2018-03-12 22:42 UTC, bendrucker commented on index.js
> +  let result = null
Return early, don't declare "result" and conditionally assign to it

2018-03-12 22:42 UTC, bendrucker commented on test.js
> +  console.log('--------------\r\n\r\n')
👎👎:-1::pray:

2018-03-12 22:42 UTC, bendrucker commented on test.js
> +test('exact versions -> true', function (t) {
exact versions

2018-03-12 22:42 UTC, bendrucker commented on test.js
> +  t.ok(exact('4.0.0'), 'Typical 3-tiered version number')
`n.n.n`

2018-03-12 22:42 UTC, bendrucker commented on test.js
> +  t.ok(exact('1.8.3-beta.1'), 'Tagged version')
lowercase for the assertion message

2018-03-12 22:42 UTC, bendrucker commented on test.js
> +  t.ok(exact('=4.0.0'), "= (this doesn't appear to be part of the official spec)")
`=n.n.n`. Don't put your notes/write with a speculative voice in test assertions.

2018-03-12 22:42 UTC, bendrucker commented on test.js
> +test('range versions -> false', function (t) {
`range version`

2018-03-12 22:42 UTC, bendrucker commented on test.js
> +  t.notOk(exact(''), 'Blank/empty is the same as *')
Empty string

2018-03-12 22:42 UTC, bendrucker commented on test.js
> +  t.notOk(exact('*'), '* means anything')
`*`

Same goes for all the other assertions. Don't write them like comments.

2018-03-12 22:42 UTC, bendrucker commented on test.js
> +  t.notOk(exact('~4.0.0'), '~ specifies as range')
This test section is called `range`, keep the messages as concise as possible

2018-03-12 22:42 UTC, bendrucker commented on test.js
> +test('exact commitish strings -> true', function (t) {
Move these to the main exact suite. There should be two `test` calls, one for exact, one for ranges.

Don't construct test assertions in a complex loop when you can avoid it. You can generate all your test "version" identifiers ahead of time using your URLs and refs.

2018-03-12 22:42 UTC, bendrucker commented on test.js
> +  '#jj-abrams',
Pull this out, it's not distinct from `#master`

2018-03-12 22:46 UTC, jacobq commented on test.js
> +  '#jj-abrams',
It contains a `-` which could be mistakenly identified as a range operator

2018-03-12 22:47 UTC, jacobq commented on test.js
> +  '#jj-abrams',
If we wanted to make our lives harder we could test `#1.0.0-1.2.0`, which could be a valid (though misleading) exact tag but looks very similar to `#semver:1.0.0-1.2.0` which would be a range.

2018-03-12 23:02 UTC, jacobq commented on index.js
> +  let result = null
If you think that
```js
function extractSemVer (s) {
  const match = s.match(nestedSemVerRegEx)
  return match && match[1]
}
```
is more readable then so be it :trollface:

2018-03-12 23:05 UTC, jacobq commented on test.js
> +  t.notOk(exact(''), 'Blank/empty is the same as *')
Done. However, I think there is some merit to the idea of expressing *why* something is the way it is. There are quite a few "grey areas" regarding what an "exact" version is so there is potential for confusion. The test suite can serve to resolve any ambiguity.

2018-03-12 23:07 UTC, jacobq commented on index.js
> +const rangeRegEx = /^$|[\^*~<>|]|(\d+\.x)|(\d+(\.\d)*\s*-\s*\d+(\.\d)*)/
You may want to consider eliminating the use of regex altogether. I think there are some standard functions in the [`semver` package](https://www.npmjs.com/package/semver) that might help.

2018-03-13 00:49 UTC, bendrucker commented on test.js
> +const generateUrls = (baseURLs, refs) => {
Use a function declaration and put it at the end of the file. Don't use arrow functions except as one-liners or to bind `this`.

2018-03-13 00:49 UTC, bendrucker commented on test.js
> +    return urls.concat(refs.map(ref => `${baseURL}${ref}`))
Avoid template strings when concatenation is clearer: `baseURL + ref`

2018-03-13 00:49 UTC, bendrucker commented on index.js
> +  if (typeof versionString !== 'string') {
Don't think we need to handle non-strings

2018-03-13 00:49 UTC, bendrucker commented on test.js
> +const generateUrls = (baseURLs, refs) => {
You can also do `urls = ` in each test callback for the respective case. The idea is just that the test cases not be generated in a loop for easier debugging. If you call your helper twice that's still accomplished.

2018-03-13 00:49 UTC, bendrucker commented on index.js
> +const rangeRegEx = /^$|[\^*~<>|]|(\d+\.x)|(\d+(\.\d)*\s*-\s*\d+(\.\d)*)/
Yeah that's what I meant

2018-11-02 21:54 UTC, jacobq commented
Closing in favor of https://github.com/jacobq/is-exact-version

2018-11-02 21:54 UTC, closed without merging